//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleCamera
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Attrs
        {
            
            public const int mapType = 0x7f010000;
            
            public const int cameraBearing = 0x7f010001;
            
            public const int cameraTargetLat = 0x7f010002;
            
            public const int cameraTargetLng = 0x7f010003;
            
            public const int cameraTilt = 0x7f010004;
            
            public const int cameraZoom = 0x7f010005;
            
            public const int uiCompass = 0x7f010006;
            
            public const int uiRotateGestures = 0x7f010007;
            
            public const int uiScrollGestures = 0x7f010008;
            
            public const int uiTiltGestures = 0x7f010009;
            
            public const int uiZoomControls = 0x7f01000a;
            
            public const int uiZoomGestures = 0x7f01000b;
            
            public const int useViewLifecycle = 0x7f01000c;
            
            public const int zOrderOnTop = 0x7f01000d;
        }
        
        public sealed class Drawables
        {
            
            public const int common_signin_btn_icon_dark = 0x7f020000;
            
            public const int common_signin_btn_icon_disabled_dark = 0x7f020001;
            
            public const int common_signin_btn_icon_disabled_focus_dark = 0x7f020002;
            
            public const int common_signin_btn_icon_disabled_focus_light = 0x7f020003;
            
            public const int common_signin_btn_icon_disabled_light = 0x7f020004;
            
            public const int common_signin_btn_icon_focus_dark = 0x7f020005;
            
            public const int common_signin_btn_icon_focus_light = 0x7f020006;
            
            public const int common_signin_btn_icon_light = 0x7f020007;
            
            public const int common_signin_btn_icon_normal_dark = 0x7f020008;
            
            public const int common_signin_btn_icon_normal_light = 0x7f020009;
            
            public const int common_signin_btn_icon_pressed_dark = 0x7f02000a;
            
            public const int common_signin_btn_icon_pressed_light = 0x7f02000b;
            
            public const int common_signin_btn_text_dark = 0x7f02000c;
            
            public const int common_signin_btn_text_disabled_dark = 0x7f02000d;
            
            public const int common_signin_btn_text_disabled_focus_dark = 0x7f02000e;
            
            public const int common_signin_btn_text_disabled_focus_light = 0x7f02000f;
            
            public const int common_signin_btn_text_disabled_light = 0x7f020010;
            
            public const int common_signin_btn_text_focus_dark = 0x7f020011;
            
            public const int common_signin_btn_text_focus_light = 0x7f020012;
            
            public const int common_signin_btn_text_light = 0x7f020013;
            
            public const int common_signin_btn_text_normal_dark = 0x7f020014;
            
            public const int common_signin_btn_text_normal_light = 0x7f020015;
            
            public const int common_signin_btn_text_pressed_dark = 0x7f020016;
            
            public const int common_signin_btn_text_pressed_light = 0x7f020017;
            
            public const int Icon = 0x7f020018;
        }
        
        public sealed class Colors
        {
            
            public const int common_signin_btn_dark_text_default = 0x7f030000;
            
            public const int common_signin_btn_dark_text_pressed = 0x7f030001;
            
            public const int common_signin_btn_dark_text_disabled = 0x7f030002;
            
            public const int common_signin_btn_dark_text_focused = 0x7f030003;
            
            public const int common_signin_btn_light_text_default = 0x7f030004;
            
            public const int common_signin_btn_light_text_pressed = 0x7f030005;
            
            public const int common_signin_btn_light_text_disabled = 0x7f030006;
            
            public const int common_signin_btn_light_text_focused = 0x7f030007;
            
            public const int common_signin_btn_default_background = 0x7f030008;
            
            public const int common_action_bar_splitter = 0x7f030009;
            
            public const int common_signin_btn_text_dark = 0x7f03000a;
            
            public const int common_signin_btn_text_light = 0x7f03000b;
        }
        
        public sealed class Ids
        {
            
            public const int none = 0x7f040035;
            
            public const int normal = 0x7f040036;
            
            public const int satellite = 0x7f040037;
            
            public const int terrain = 0x7f040038;
            
            public const int hybrid = 0x7f040039;
        }
        
        public sealed class Strings
        {
            
            public const int common_google_play_services_install_title = 0x7f050000;
            
            public const int common_google_play_services_install_text_phone = 0x7f050001;
            
            public const int common_google_play_services_install_text_tablet = 0x7f050002;
            
            public const int common_google_play_services_install_button = 0x7f050003;
            
            public const int common_google_play_services_enable_title = 0x7f050004;
            
            public const int common_google_play_services_enable_text = 0x7f050005;
            
            public const int common_google_play_services_enable_button = 0x7f050006;
            
            public const int common_google_play_services_update_title = 0x7f050007;
            
            public const int common_google_play_services_update_text = 0x7f050008;
            
            public const int common_google_play_services_unknown_issue = 0x7f050009;
            
            public const int common_google_play_services_unsupported_title = 0x7f05000a;
            
            public const int common_google_play_services_unsupported_text = 0x7f05000b;
            
            public const int common_google_play_services_update_button = 0x7f05000c;
            
            public const int common_signin_button_text = 0x7f05000d;
            
            public const int common_signin_button_text_long = 0x7f05000e;
            
            public const int auth_client_using_bad_version_title = 0x7f05000f;
            
            public const int auth_client_needs_enabling_title = 0x7f050010;
            
            public const int auth_client_needs_installation_title = 0x7f050011;
            
            public const int auth_client_needs_update_title = 0x7f050012;
            
            public const int auth_client_play_services_err_notification_msg = 0x7f050013;
            
            public const int auth_client_requested_by_msg = 0x7f050014;
        }
        
        public sealed class Styleables
        {
            
            public sealed class MapAttrs
            {
                
                public const int mapType = R.Attrs.mapType & 0xffff;
                
                public const int cameraBearing = R.Attrs.cameraBearing & 0xffff;
                
                public const int cameraTargetLat = R.Attrs.cameraTargetLat & 0xffff;
                
                public const int cameraTargetLng = R.Attrs.cameraTargetLng & 0xffff;
                
                public const int cameraTilt = R.Attrs.cameraTilt & 0xffff;
                
                public const int cameraZoom = R.Attrs.cameraZoom & 0xffff;
                
                public const int uiCompass = R.Attrs.uiCompass & 0xffff;
                
                public const int uiRotateGestures = R.Attrs.uiRotateGestures & 0xffff;
                
                public const int uiScrollGestures = R.Attrs.uiScrollGestures & 0xffff;
                
                public const int uiTiltGestures = R.Attrs.uiTiltGestures & 0xffff;
                
                public const int uiZoomControls = R.Attrs.uiZoomControls & 0xffff;
                
                public const int uiZoomGestures = R.Attrs.uiZoomGestures & 0xffff;
                
                public const int useViewLifecycle = R.Attrs.useViewLifecycle & 0xffff;
                
                public const int zOrderOnTop = R.Attrs.zOrderOnTop & 0xffff;
                
public static readonly int[] AllIds = new[] { R.Attrs.mapType, R.Attrs.cameraBearing, R.Attrs.cameraTargetLat, R.Attrs.cameraTargetLng, R.Attrs.cameraTilt, R.Attrs.cameraZoom, R.Attrs.uiCompass, R.Attrs.uiRotateGestures, R.Attrs.uiScrollGestures, R.Attrs.uiTiltGestures, R.Attrs.uiZoomControls, R.Attrs.uiZoomGestures, R.Attrs.useViewLifecycle, R.Attrs.zOrderOnTop };
            }
        }
    }
}
